#!/usr/bin/python3
import sys



def factorize(n):

    for i in range(2, n):

        if n % i == 0:

            return (i, n // i)

    return (n, 1)



def main():

    for line in sys.stdin:

        n = int(line)

        p, q = factorize(n)

        print(f"{n}={p}*{q}")



if __name__ == "__main__":

    main()
